services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: invitation_system
      POSTGRES_USER: invitation_user
      POSTGRES_PASSWORD: strong_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invitation_user -d invitation_system"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_NAME: invitation_system
      DATABASE_USER: invitation_user
      DATABASE_PASSWORD: strong_password_123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      PYTHONUNBUFFERED: 1

volumes:
  postgres_data: